make compatible with config-cache
dropbox/dropshots pull request #26
Opened 2022-08-11 19:29 UTC by devPalacio

Minor change to make the plugin compatible with config-cache. 

Used the guide here: https://docs.gradle.org/7.5/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

2022-08-11 19:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dropbox/dropshots?pullRequest=26) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dropbox/dropshots?pullRequest=26) before we can accept your contribution.<br/><hr/>**Jay Palacio** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dropbox/dropshots?pullRequest=26) it.</sub>

2022-08-11 20:22 UTC, joshafeinberg approved these changes

2022-08-11 22:47 UTC, rharter commented on dropshots-gradle-plugin/src/main/kotlin/com/dropbox/dropshots/ClearScreenshotsTask.kt
> +  protected abstract fun getExecOperations(): ExecOperations
Can these be made into `val`s?

2022-08-11 22:48 UTC, rharter requested changes
Thanks for the contribution! Would you mind updating the injected functions to vals just to be consistent?

2022-08-12 02:40 UTC, devPalacio commented on dropshots-gradle-plugin/src/main/kotlin/com/dropbox/dropshots/ClearScreenshotsTask.kt
> +  protected abstract fun getExecOperations(): ExecOperations
Got it!

2022-08-12 12:44 UTC, devPalacio commented
Changed as requested.

2022-08-12 20:47 UTC, rharter approved these changes
Awesome, thanks!

2022-08-12 20:48 UTC, merged